### ISSUE TITLE
Unify the virtual environment recommendations

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-smi#16]
It would be good to unify the virtual environment recommendation on all of tt-flash, tt-smi and https://docs.tenstorrent.com/tenstorrent/apis-sdks-and-software/software-and-utilities 

cc @adifrancescoTT

**Comment by warthog9** [comment]
I'm confused on what the request is here.  Noting that each of the repositories' you've noted, it's README.md is targeted at developers, not end users.  There's not really a way per-se to "unify" the comments on virtual envs, as each repo is going to make a reminder note that you can use a virtual env, and have some basic instructions, but again since the docs are more targeted at developers I'm expecting they likely already have a basic idea of what a venv is, how it works, and may even have strong opinions on which flavor of venv they would prefer to use.

So I guess, is this more a developer facing bug, if so we need this duplicated into the respective repositories, as well as a clearer understanding of what's needed there.

If this is more a user facing bug, most end users should be using https://docs.tenstorrent.com/tenstorrent/add-in-boards-and-cooling-kits/grayskull-tm-e75-e150/software-setup as that's targeted at end users, not specifically developers.
